services:
  redis:
    image: redis:7-alpine
    container_name: marinkino-redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis_data:/data
    command: redis-server --dir /data --dbfilename dump.rdb --appendonly no
    networks:
      - marinkino-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marinkino-app
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./cache:/app/cache
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - marinkino-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: marinkino-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configuration/nginx/conf:/etc/nginx/conf.d:ro
      - ./configuration/certbot/www:/var/www/certbot:ro
      - ./configuration/certbot/conf:/etc/letsencrypt:ro
      - ./data/music:/music_data
      - ./data/movies:/movies_data
      - ./data/memes:/memes_data
    networks:
      - marinkino-network
    restart: unless-stopped
    # Nginx se ponovno nalo≈æi vsakih 6 ur, da pobere nove certifikate
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: marinkino-certbot
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./configuration/certbot/www:/var/www/certbot:rw
      - ./configuration/certbot/conf:/etc/letsencrypt:rw
    # Ta ukaz preverja certifikate vsakih 12 ur
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
networks:
  marinkino-network:
    driver: bridge
